version: "3.7"
services:

  #Laravel App
  app:
    build:
      args:
        user: chat
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: chat-app
    restart: unless-stopped
    environment:
      NODE_HOST: http://host.docker.internal:3000
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - chatnetwork

  #Nginx Service
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - chatnetwork

  #Mysl Service
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - chatnetwork

networks:
  chatnetwork:
    driver: bridge
    name: chatnetwork
